name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Basic Test
        run: |
          python -m py_compile app.py

      - name: Build Docker Image
        run: |
          docker build -t devsecops-demo:v1 .

      - name: Attack - Privilege Abuse
        env:
          MY_SECRET_TOKEN: ${{ secrets.HACKER_TOKEN }}
        run: |
          echo "Memulai serangan..."
          git config --global user.email "#exploit00@devil.com#"
          git config --global user.name "#Anonim#"
          
          echo "BERHASIL TEMBUS" > malware.txt
          
          # Kita pastikan token terdeteksi (GitHub akan menyensornya dengan ***)
          echo "Token check: $MY_SECRET_TOKEN"
          
          git add malware.txt
          git commit -m "Simulate pipeline privilege abuse"
          
          # Gunakan variabel env dengan tanda kutip agar aman
          git push --force "https://x-access-token:${MY_SECRET_TOKEN}@github.com/${{ github.repository }}.git" main