name: Test Audit Log DevSecOps

on:
  push:
    branches: [ main ]

jobs:
  simulate-attack:
    runs-on: ubuntu-latest
    steps:
      - name: Memicu Kegagalan Sistem
        run: |
          echo "Simulasi interupsi keamanan pada pipeline..."
          exit 1
